// Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.

// This software is the property of WSO2 LLC. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein is strictly forbidden, unless permitted by WSO2 in accordance with
// the WSO2 Software License available at: https://wso2.com/licenses/eula/3.2
// For specific language governing the permissions and limitations under
// this license, please see the license as well as any agreement you’ve
// entered into with WSO2 governing the purchase of this software and any
// associated services.
//
//
// AUTO-GENERATED FILE.
//
// This file is auto-generated by WSO2 Healthcare Team for managing utility functions.
// Developers are allowed modify this file as per the requirement.

import ballerinax/health.fhir.r4;

final r4:ResourceAPIConfig apiConfig = {
    resourceType: "MedicinalProductPharmaceutical",
    profiles: [
            "http://hl7.org/fhir/StructureDefinition/MedicinalProductPharmaceutical"        
    ],
    defaultProfile: (),
    searchParameters: [
            {
        name: "identifier",
        active: true,
        information: {
            description: "An identifier for the pharmaceutical medicinal product",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/MedicinalProductPharmaceutical-identifier"
        }
    },
            {
        name: "target-species",
        active: true,
        information: {
            description: "Coded expression for the species",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/MedicinalProductPharmaceutical-target-species"
        }
    },
            {
        name: "route",
        active: true,
        information: {
            description: "Coded expression for the route",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/MedicinalProductPharmaceutical-route"
        }
    }
        ],
    operations: [
    
    ],
    serverConfig: (),
    authzConfig: ()
};
