[package]
org = "ballerinax"
name = "health.fhir.templates.r4.patient"
version = "1.0.4-snapshot"
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Patient", "r4", "international"]
template = true
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhirr4"
version = "1.0.8"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "1.0.0"


