[package]
org = "ballerinax"
name = "health.fhir.templates.r4.patient"
version = "1.0.2"
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Patient", "r4", "international"]
template = true
repository="https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "1.0.2"

[[dependency]]
org = "ballerinax"
name = "health.base"
version = "1.0.1"

