[package]
org = "ballerinax"
name = "health.fhir.templates.international401.contract"
version = "2.0.1"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Contract", "r4", "health.fhir.templates.international401"]
template = true
