[package]
org = "ballerinax"
name = "health.fhir.templates.r4.metadata"
version = "1.0.1-snapshot"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Metadata"]
distribution = "2201.4.1"
include = ["Cloud.toml", "Config.toml"]
export = [
    "health.fhir.templates.r4.metadata.config",
    "health.fhir.templates.r4.metadata.constants",
    "health.fhir.templates.r4.metadata.handlers",
    "health.fhir.templates.r4.metadata.models",
    "health.fhir.templates.r4.metadata.samples"
]
template = true
repository="https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
