[package]
org = "ballerinax"
name = "health.fhir.templates.r4.metadata"
version = "1.1.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Metadata"]
distribution = "2201.7.0"
include = ["Cloud.toml", "Config.toml"]
template = true
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

