[package]
org = "ballerinax"
name = "health.fhir.templates.international401.plandefinition"
version = "2.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "PlanDefinition", "r4", "health.fhir.templates.international401"]
template = true
