[package]
org = "ballerinax"
name = "health.fhir.templates.r4.smartconfiguration"
version = "1.0.1-snapshot"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "SMART"]
distribution = "2201.4.1"
include = ["Config.toml"]
export = [
    "health.fhir.templates.r4.smartconfiguration.config",
    "health.fhir.templates.r4.smartconfiguration.constants",
    "health.fhir.templates.r4.smartconfiguration.handlers",
    "health.fhir.templates.r4.smartconfiguration.models"
]
template = true
repository="https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
