[package]
org = "ballerinax"
name = "health.fhir.templates.r4.smartconfiguration"
version = "1.0.2-snapshot"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "SMART"]
distribution = "2201.5.0"
include = ["Config.toml"]
template = true
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
